# Generated by Django 5.1.6 on 2025-03-02 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Título del libro')),
                ('cod', models.CharField(max_length=15, unique=True, verbose_name='Codigo')),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.author')),
            ],
        ),
    ]
